### PR TITLE
Merging terraforming into main

### PR DESCRIPTION
**Pull request by julianxcarter**
Brings master up to date with changed made to the terraforming branch including:

* Terraforming scripts for auto-building the AWS environment 
* STU2 updates to the Extraction lambda
* Duplicate row checking in the Extraction lambda
* Updated SSL certificates for the process message and extraction lambdas

Also includes a GitHub Actions file for unit tests, and updates to the `.eslintrc` file to make use of prettier's formatting rules.

### CODE REVIEW

**Comment by Dtphelan1** [comment]
DP2 - I see we have a `yarn.lock` file, but I don't see yarn mentioned in the setup instructions. Do we still need this file?

**Comment by Dtphelan1** [comment]
Other than those three things, this looks good to me!

**Comment by julianxcarter** [comment]
> Other than those three things, this looks good to me!

All great points! The most recent commits add `Linting` and `Terraforming` sections to the readme, remove the `yarn.lock` file, and also removes the rogue `.DS_Store` file and updates the gitignore to not include them in the future.

**Review by Dtphelan1 — APPROVED** [review]
Definitely addresses all my questions. Great work Julian 😊

**Pull request merged**
