### PR TITLE
Extraction no longer allows duplicate rows in output

### PR DESCRIPTION
**Pull request by dmendelowitz**
## Summary
When the extraction lambda adds a new row to a worksheet it will now check if it is identical to any other rows in the sheet and if it is, it will be removed. I also switched to a newer version of fhirpath because it was causing an error related to antlr.

## Testing guidance
Run the Base ICARE Extraction Client twice with the same parameters to induce duplicates, then run the Extraction Lambda and ensure that there are no duplicate rows in the output.

### CODE REVIEW

**Review by julianxcarter — APPROVED** [review]
This works as advertised! I know that the task was to remove duplicate entries from the worksheet, but I'm actually wondering if it'd be better to just preemptively not add rows if we find a duplicate row already exists. The current method leaves a large amount of blank rows in the exported excel sheet that I think we could avoid by generating the row object ahead of the `worksheet.addRow()` call, checking this object against the values on our pre-existing rows, and then adding the new row to the worksheet if that checks out. I'm approving because I tested this and it works well, but I'm wondering what others think.

**Comment by dmendelowitz** [comment]
> This works as advertised! I know that the task was to remove duplicate entries from the worksheet, but I'm actually wondering if it'd be better to just preemptively not add rows if we find a duplicate row already exists. The current method leaves a large amount of blank rows in the exported excel sheet that I think we could avoid by generating the row object ahead of the `worksheet.addRow()` call, checking this object against the values on our pre-existing rows, and then adding the new row to the worksheet if that checks out. I'm approving because I tested this and it works well, but I'm wondering what others think.

The reason I ended up doing the add, check for dupes, then remove method was to get the data in the same format for easy comparison. The new row (before being added to the sheet) is an object while getting a row from the worksheet returned an array with a weird null value in the first spot. So what you're describing is possible, it would just require some reformatting/sorting before comparing rows. If you think that's better I'm willing to make the changes.

**Comment by julianxcarter** [comment]
> The reason I ended up doing the add, check for dupes, then remove method was to get the data in the same format for easy comparison. The new row (before being added to the sheet) is an object while getting a row from the worksheet returned an array with a weird null value in the first spot. So what you're describing is possible, it would just require some reformatting/sorting before comparing rows. If you think that's better I'm willing to make the changes.

It's not something that I feel super strongly about, I just wanted to see if you had considered that and it looks like you did! This approach works, and I don't think empty rows will be detrimental to anyone in the ICAREData program so I think it's fine as is. We can check with Rob to see if he thinks the change is worth it, but I'm fine with this as it stands.

**Comment by Dtphelan1** [comment]
I thinkkkkk this looks great, but there was one weird result I got on one of my tests – one of my unzipped worksheets had several empty rows inbetween a valid and an invalid row. Did either of you two see that in your testing? Overall this functionality works as expected, but it might be problematic if our table has randomly empty rows in its middle. Thoughts?

**Comment by dmendelowitz** [comment]
> I thinkkkkk this looks great, but there was one weird result I got on one of my tests – one of my unzipped worksheets had several empty rows inbetween a valid and an invalid row. Did either of you two see that in your testing? Overall this functionality works as expected, but it might be problematic if our table has randomly empty rows in its middle. Thoughts?

I think both this and the empty rows Julian mentioned are related to `spliceRow()` which I encountered some weirdness with. I'm going to test out a few more things before we call this task done, I think I may just be using the function wrong

**Comment by Dtphelan1** [comment]
I think that's worthwhile. Let me know if you wanna bounce ideas around in the WS.

**Comment by dmendelowitz** [comment]
So, while I couldn't replicate Dylan P's bug, my current suspicion about the source of any weirdness is that there is a known bug in exceljs related to trying to use `spliceRows()` on the last row of a worksheet (https://github.com/exceljs/exceljs/issues/474). If things were working as they should, I should have been able to use `spliceRows(worksheet.rowCount, 1)` to just remove the last row, but due to the bug, I had to use `spliceRows(worksheet.rowCount, 1, [])` to splice an empty row on top of the row I wanted to remove.

If this becomes a problem in the future, I think we could definitely use a different method of preventing duplicates, but since we had difficulty replicating the problem, I think it may be fine as it is for now. Does that all make sense?

**Review by Dtphelan1 — APPROVED** [review]

**Pull request merged**
