### PR TITLE
Updated the valueset to use actual ICD10 codes

### PR DESCRIPTION
**Pull request by Dtphelan1**
Updates the secondary-condition valueset to use actual ICD-10 codes, and updates fixtures accordingly. After talking with @kjmahalingam, this PR also removes the expansion from the ValueSet. 

Looks like some linter madness took over too. If people are particularly finicky I can remove it, but I couldn't be bothered. 😆

### CODE REVIEW

**Review by kjmahalingam — APPROVED** [review]
This looks good and works well!

**Review by kjmahalingam — APPROVED** [review]

**Review by kjmahalingam — CHANGES_REQUESTED** [review]
Turns out we do want to have the expansion in this VS, and therefore my approval was erroneous. 😢

**Comment by Dtphelan1** [comment]
The removed expansion should be remedied with the most recent commits.

**Review by jafeltra — APPROVED** [review]
Looks good to me now!

**Review by kjmahalingam — APPROVED** [review]

**Pull request merged**
